# Generated by Django 3.2.4 on 2021-07-06 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 3, 48, 41, 56721, tzinfo=utc)),
        ),
    ]
