# Generated by Django 3.2.4 on 2021-07-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_myuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
