# Generated by Django 3.2.4 on 2021-07-07 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_myuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
