# Generated by Django 3.2.4 on 2021-07-07 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_blog_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title_slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
