# Generated by Django 3.2.4 on 2021-07-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_blog_title_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title_slug',
        ),
    ]
