# Generated by Django 3.2.4 on 2021-07-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210714_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
